language: php
php:
  - '5.6.32'
  - '7.0.25'
  - '7.1.11'
install:
  - composer update && composer dump-autoload
before_script:
  - npm install
  - mkdir -p build/logs
script:
  - vendor/bin/phpunit --testsuite CoreTestUnitSuite
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/php-coveralls -v; fi;'
