language: php
php:
  - '7.1.12'
  - '7.2'
install:
  - composer update && composer dump-autoload
before_script:
  - npm install
  - mkdir -p build/logs
script:
  - vendor/bin/phpunit --testsuite CoreTestUnitSuite
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
